apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
- namespace.yaml
- prometheus-operator.yaml
- fluent-bit.yaml
- ingress.yaml
- sre-challenge-dashboard.yaml
# ServiceMonitors will be added after Prometheus Operator is ready
# - servicemonitors.yaml

commonLabels:
  app.kubernetes.io/name: monitoring-stack
  app.kubernetes.io/instance: staging
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/component: monitoring
  app.kubernetes.io/part-of: sre-challenge
  app.kubernetes.io/managed-by: flux

patchesStrategicMerge:
- |-
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: monitoring-ingress
    namespace: monitoring
  spec:
    rules:
    - host: prometheus.eu-central-1.sre-challenge-panther.network
    - host: grafana.eu-central-1.sre-challenge-panther.network