apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
- namespace.yaml
- prometheus-operator.yaml
- fluent-bit.yaml
- simple-ingress.yaml
- sre-challenge-dashboard.yaml
- servicemonitors.yaml
- node-health-dashboard.yaml
- application-health-dashboard.yaml

commonLabels:
  app.kubernetes.io/name: monitoring-stack
  app.kubernetes.io/instance: staging
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/component: monitoring
  app.kubernetes.io/part-of: sre-challenge
  app.kubernetes.io/managed-by: flux

