apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sre-challenge-app
  namespace: monitoring
  labels:
    app: sre-challenge-app
    environment: staging
spec:
  selector:
    matchLabels:
      app: sre-challenge-app
  namespaceSelector:
    matchNames:
    - sre-challenge
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    honorLabels: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-system
  namespace: monitoring
  labels:
    app: flux-system
    environment: staging
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: flux
  namespaceSelector:
    matchNames:
    - flux-system
  endpoints:
  - port: http-prom
    interval: 30s
    path: /metrics
    honorLabels: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aws-load-balancer-controller
  namespace: monitoring
  labels:
    app: aws-load-balancer-controller
    environment: staging
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: aws-load-balancer-controller
  namespaceSelector:
    matchNames:
    - kube-system
  endpoints:
  - port: webhook-server
    interval: 30s
    path: /metrics
    honorLabels: true