{
 "title": "SRE Challenge Application Dashboard",
 "tags": [
  "kubernetes",
  "sre-challenge"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "SRE Challenge App Availability",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"sre-challenge-app\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"sre-challenge\",pod=~\"sre-challenge-app-.*\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"sre-challenge\",pod=~\"sre-challenge-app-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_ready{namespace=\"sre-challenge\",deployment=\"sre-challenge-app\"}",
     "legendFormat": "Ready Replicas"
    },
    {
     "expr": "kube_deployment_spec_replicas{namespace=\"sre-challenge\",deployment=\"sre-challenge-app\"}",
     "legendFormat": "Desired Replicas"
    }
   ]
  }
 ]
}